# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alerts.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1100, 541)
        Form.setStyleSheet("#Form{\n"
"background-color: #b0c1d9;\n"
"color: white;\n"
"padding: 10px 20px;\n"
"margin-top: 0;\n"
"margin-left: 0;\n"
"margin-right:0;\n"
"}\n"
"\n"
"\n"
"")
        self.alerts = QtWidgets.QScrollArea(Form)
        self.alerts.setGeometry(QtCore.QRect(29, 49, 1041, 481))
        self.alerts.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 11pt \"Segoe UI\";\n"
"border-color: rgb(0, 0, 0);\n"
"padding: 10px")
        self.alerts.setWidgetResizable(True)
        self.alerts.setObjectName("alerts")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1019, 459))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
#         self.notify = QtWidgets.QWidget(self.scrollAreaWidgetContents)
#         self.notify.setGeometry(QtCore.QRect(180, 0, 671, 91))
#         self.notify.setStyleSheet("#notify{\n"
# "background-color:  rgb(13, 30, 64);\n"
# "border-radius: 25px;\n"
# "color: white;\n"
# "padding: 10px 20px;\n"
# "}")
#         self.notify.setObjectName("notify")
#         self.label = QtWidgets.QLabel(self.notify)
#         self.label.setGeometry(QtCore.QRect(90, 40, 251, 41))
#         self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
# "font: 700 12pt \"Segoe UI\";\n"
# "background-color: rgb(13, 30, 64);")
#         self.label.setObjectName("label")
#         self.preview = QtWidgets.QPushButton(self.notify)
#         self.preview.setGeometry(QtCore.QRect(510, 50, 131, 31))
#         font = QtGui.QFont()
#         font.setFamily("Segoe UI")
#         font.setPointSize(8)
#         font.setBold(False)
#         font.setItalic(False)
#         self.preview.setFont(font)
#         self.preview.setStyleSheet("#preview{\n"
# "    font: 8pt \"Segoe UI\";\n"
# "background-color: rgb(48, 131, 59);\n"
# "border-radius: 15px;\n"
# "color: white;\n"
# "padding: 10px 20px;\n"
# "}\n"
# "\n"
# "#preview:hover {\n"
# "background-color: #0D1E40;\n"
# "border-radius: 15px;\n"
# "color: white;\n"
# "}\n"
# "")
#         self.preview.setObjectName("preview")
#         self.time = QtWidgets.QLabel(self.notify)
#         self.time.setGeometry(QtCore.QRect(20, 10, 221, 31))
#         self.time.setStyleSheet("color: rgb(255, 255, 255);\n"
# "font: 9pt \"Segoe UI\";\n"
# "font: 700 10pt \"Segoe UI\";\n"
# "background-color: rgb(13, 30, 64);")
#         self.time.setObjectName("time")
        self.alerts.setWidget(self.scrollAreaWidgetContents)
        self.refresh = QtWidgets.QLabel(Form)
        self.refresh.setGeometry(QtCore.QRect(1020, 20, 21, 21))
        self.refresh.setText("")
        self.refresh.setPixmap(QtGui.QPixmap("resources/refreshIcon.png"))
        self.refresh.setScaledContents(True)
        self.refresh.setObjectName("refresh")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        # self.label.setText(_translate("Form", "Violence detected!"))
        # self.preview.setText(_translate("Form", "Preview"))
        # self.time.setText(_translate("Form", "12/02/24  24:22:23"))
