# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'facial.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_facial(object):
    def setupUi(self, facial):
        facial.setObjectName("facial")
        facial.resize(1100, 540)
        facial.setStyleSheet("#facial{\n"
"background-color: #b0c1d9;\n"
"color: white;\n"
"padding: 10px 20px;\n"
"margin-top: 0;\n"
"margin-left: 0;\n"
"margin-right:0;\n"
"}\n"
"\n"
"\n"
"")
        self.image = QtWidgets.QWidget(facial)
        self.image.setGeometry(QtCore.QRect(30, 70, 431, 361))
        self.image.setStyleSheet("#image{\n"
"background-color: rgb(13, 30, 64);\n"
"border-radius:15px;\n"
"}\n"
"")
        self.image.setObjectName("image")
        self.startFacial = QtWidgets.QPushButton(facial)
        self.startFacial.setGeometry(QtCore.QRect(330, 460, 121, 31))
        self.startFacial.setStyleSheet("#startFacial{\n"
"background-color: rgb(48, 131, 59);\n"
"border-radius: 15px;\n"
"color: white;\n"
"padding: 10px 20px;\n"
"}\n"
"\n"
"#startFacial:hover {\n"
"background-color: #0D1E40;\n"
"border-radius: 15px;\n"
"color: white;\n"
"}\n"
"")
        self.startFacial.setObjectName("startFacial")
        self.cancel_image = QtWidgets.QPushButton(facial)
        self.cancel_image.setGeometry(QtCore.QRect(180, 460, 111, 31))
        self.cancel_image.setStyleSheet("#cancel_image{\n"
"background-color: rgb(48, 131, 59);\n"
"border-radius: 15px;\n"
"color: white;\n"
"padding: 10px 20px;\n"
"}\n"
"\n"
"#cancel_image:hover {\n"
"background-color: #0D1E40;\n"
"border-radius: 15px;\n"
"color: white;\n"
"}\n"
"")
        self.cancel_image.setObjectName("cancel_image")
        self.browse = QtWidgets.QPushButton(facial)
        self.browse.setGeometry(QtCore.QRect(30, 460, 111, 31))
        self.browse.setStyleSheet("#browse{\n"
"background-color: rgb(48, 131, 59);\n"
"border-radius: 15px;\n"
"color: white;\n"
"padding: 10px 20px;\n"
"}\n"
"\n"
"#browse:hover {\n"
"background-color: #0D1E40;\n"
"border-radius: 15px;\n"
"color: white;\n"
"}\n"
"")
        self.browse.setObjectName("browse")
        self.imageprocessing = QtWidgets.QWidget(facial)
        self.imageprocessing.setGeometry(QtCore.QRect(580, 10, 501, 481))
        self.imageprocessing.setStyleSheet("#imageprocessing{\n"
"    color: rgb(0, 0, 0);\n"
"background-color: white;\n"
"border-radius:15px;\n"
"}\n"
"")
        self.imageprocessing.setObjectName("imageprocessing")
        self.editImage = QtWidgets.QPushButton(facial)
        self.editImage.setGeometry(QtCore.QRect(30, 20, 111, 31))
        self.editImage.setStyleSheet("#cancel_image{\n"
"background-color: rgb(48, 131, 59);\n"
"border-radius: 15px;\n"
"color: white;\n"
"padding: 10px 20px;\n"
"}\n"
"\n"
"#cancel_image:hover {\n"
"background-color: #0D1E40;\n"
"border-radius: 15px;\n"
"color: white;\n"
"}\n"
"")
        self.editImage.setObjectName("editImage")
        self.share = QtWidgets.QPushButton(facial)
        self.share.setGeometry(QtCore.QRect(720, 500, 111, 31))
        self.share.setStyleSheet("#share{\n"
"background-color: rgb(48, 131, 59);\n"
"border-radius: 15px;\n"
"color: white;\n"
"padding: 10px 20px;\n"
"}\n"
"\n"
"#share:hover {\n"
"background-color: #0D1E40;\n"
"border-radius: 15px;\n"
"color: white;\n"
"}\n"
"")
        self.share.setObjectName("share")
        self.print = QtWidgets.QPushButton(facial)
        self.print.setGeometry(QtCore.QRect(840, 500, 111, 31))
        self.print.setStyleSheet("#print{\n"
"background-color: rgb(48, 131, 59);\n"
"border-radius: 15px;\n"
"color: white;\n"
"padding: 10px 20px;\n"
"}\n"
"\n"
"#print:hover {\n"
"background-color: #0D1E40;\n"
"border-radius: 15px;\n"
"color: white;\n"
"}\n"
"")
        self.print.setObjectName("print")

        self.retranslateUi(facial)
        QtCore.QMetaObject.connectSlotsByName(facial)

    def retranslateUi(self, facial):
        _translate = QtCore.QCoreApplication.translate
        facial.setWindowTitle(_translate("facial", "facial recognition"))
        self.startFacial.setText(_translate("facial", "start FR"))
        self.cancel_image.setText(_translate("facial", "cancel"))
        self.browse.setText(_translate("facial", "Browse"))
        self.editImage.setText(_translate("facial", "Edit Image"))
        self.share.setText(_translate("facial", "share"))
        self.print.setText(_translate("facial", "print"))
