# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preview.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_preview(object):
    def setupUi(self, preview):
        preview.setObjectName("preview")
        preview.resize(1100, 541)
        preview.setStyleSheet("#preview{\n"
"background-color: #b0c1d9;\n"
"color: white;\n"
"padding: 10px 20px;\n"
"margin-top: 0;\n"
"margin-left: 0;\n"
"margin-right:0;\n"
"}\n"
"\n"
"\n"
"")
        self.view = QtWidgets.QWidget(preview)
        self.view.setGeometry(QtCore.QRect(30, 19, 721, 431))
        self.view.setStyleSheet("\n"
"\n"
"#view{\n"
"border-radius: 15px;\n"
"background-color: rgb(13, 30, 64);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.view.setObjectName("view")
        self.playerSlider = QtWidgets.QSlider(preview)
        self.playerSlider.setGeometry(QtCore.QRect(60, 460, 681, 22))
        self.playerSlider.setOrientation(QtCore.Qt.Horizontal)
        self.playerSlider.setObjectName("player")
        self.playTime = QtWidgets.QLabel(preview)
        self.playTime.setGeometry(QtCore.QRect(20, 460, 49, 20))
        self.playTime.setObjectName("playTime")
        # self.startV= QtWidgets.QPushButton(preview)
        # self.startV.setGeometry(QtCore.QRect(890, 70, 81, 31))
        # font = QtGui.QFont()
        # font.setPointSize(10)
        # font.setBold(True)
        # self.startV.setFont(font)
        # self.startV.setStyleSheet("")
        # self.startV.setFlat(False)
        # self.startV.setObjectName("startV")
        self.deviceVid = QtWidgets.QPushButton(preview)
        self.deviceVid.setGeometry(QtCore.QRect(890, 140, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.deviceVid.setFont(font)
        self.deviceVid.setStyleSheet("\n"
"\n"
"#deviceVid{\n"
"border-radius: 10px;\n"
"background-color: #6077A6;\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.deviceVid.setFlat(False)
        self.deviceVid.setObjectName("deviceVid")
        
        self.play = QtWidgets.QPushButton(preview)
        self.play.setGeometry(QtCore.QRect(40, 490, 41, 24))
        self.play.setStyleSheet("\n"
"\n"
"#play{\n"
"border-radius: 10px;\n"
"background-color: #6077A6;\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.play.setObjectName("play")
        self.pause = QtWidgets.QPushButton(preview)
        self.pause.setGeometry(QtCore.QRect(90, 490, 41, 24))
        self.pause.setStyleSheet("\n"
"\n"
"#pause{\n"
"border-radius: 10px;\n"
"background-color: #6077A6;\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.pause.setObjectName("pause")
        
        
        self.label_3 = QtWidgets.QLabel(preview)
        self.label_3.setGeometry(QtCore.QRect(910, 110, 141, 21))
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 700 12pt \"Segoe UI\";")
        self.label_3.setObjectName("label_3")
        self.dataVid = QtWidgets.QPushButton(preview)
        self.dataVid.setGeometry(QtCore.QRect(990, 140, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.dataVid.setFont(font)
        self.dataVid.setStyleSheet("\n"
"\n"
"#dataVid{\n"
"border-radius: 10px;\n"
"background-color: #6077A6;\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.dataVid.setFlat(False)
        self.dataVid.setObjectName("dataVid")
        self.cancelView = QtWidgets.QPushButton(preview)
        self.cancelView.setGeometry(QtCore.QRect(140, 490, 51, 24))
        self.cancelView.setStyleSheet("\n"
"\n"
"#cancelView{\n"
"border-radius: 10px;\n"
"background-color: #6077A6;\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.cancelView.setObjectName("cancelView")

        self.retranslateUi(preview)
        QtCore.QMetaObject.connectSlotsByName(preview)

    def retranslateUi(self, preview):
        _translate = QtCore.QCoreApplication.translate
        preview.setWindowTitle(_translate("preview", "Form"))
        self.playTime.setText(_translate("preview", "56.17"))
        # self.startV.setText(_translate("preview", "S-VD"))
        self.deviceVid.setText(_translate("preview", "device"))
       
        self.play.setText(_translate("preview", "play"))
        self.pause.setText(_translate("preview", "puse"))
       
        self.label_3.setText(_translate("preview", "Browse video"))
        self.dataVid.setText(_translate("preview", "database"))
        self.cancelView.setText(_translate("preview", "Cancel"))
