# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Register(object):
    def setupUi(self, Register):
        Register.setObjectName("Register")
        Register.resize(418, 595)
        Register.setStyleSheet("#Register{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(13, 30, 64);\n"
"alignment: center;\n"
"}\n"
"")
        self.label = QtWidgets.QLabel(Register)
        self.label.setGeometry(QtCore.QRect(150, 10, 60, 57))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("resources/camera.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Register)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Register)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Register)
        self.label_4.setGeometry(QtCore.QRect(30, 170, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Register)
        self.label_5.setGeometry(QtCore.QRect(30, 210, 49, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Register)
        self.label_6.setGeometry(QtCore.QRect(30, 250, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Register)
        self.label_7.setGeometry(QtCore.QRect(90, 280, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.username = QtWidgets.QLineEdit(Register)
        self.username.setGeometry(QtCore.QRect(160, 130, 211, 22))
        self.username.setStyleSheet("#username{\n"
"border-radius: 15px;\n"
"}")
        self.username.setObjectName("username")
        self.contact = QtWidgets.QLineEdit(Register)
        self.contact.setGeometry(QtCore.QRect(160, 170, 211, 22))
        self.contact.setObjectName("contact")
        self.email = QtWidgets.QLineEdit(Register)
        self.email.setGeometry(QtCore.QRect(160, 210, 211, 22))
        self.email.setObjectName("email")
        self.work_code = QtWidgets.QLineEdit(Register)
        self.work_code.setGeometry(QtCore.QRect(160, 250, 211, 22))
        self.work_code.setObjectName("work_code")
        self.submit = QtWidgets.QPushButton(Register)
        self.submit.setGeometry(QtCore.QRect(270, 480, 111, 31))
        self.submit.setStyleSheet("#submit{\n"
"background-color: rgb(48, 131, 59);\n"
"border-radius: 15px;\n"
"color: white;\n"
"padding: 10px 20px;\n"
"}\n"
"\n"
"#submit:hover {\n"
"background-color: #0D1E40;\n"
"border-radius: 15px;\n"
"color: white;\n"
"}\n"
"")
        self.submit.setObjectName("submit")
        self.cancel = QtWidgets.QPushButton(Register)
        self.cancel.setGeometry(QtCore.QRect(120, 480, 111, 31))
        self.cancel.setStyleSheet("#cancel{\n"
"background-color: rgb(48, 131, 59);\n"
"border-radius: 15px;\n"
"color: white;\n"
"padding: 10px 20px;\n"
"}\n"
"\n"
"#cancel:hover {\n"
"background-color: #0D1E40;\n"
"border-radius: 15px;\n"
"color: white;\n"
"}\n"
"")
        self.cancel.setObjectName("cancel")
        
        self.security = QtWidgets.QRadioButton(Register)
        self.security.setGeometry(QtCore.QRect(50, 310, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.security.setFont(font)
        self.security.setStyleSheet("color: rgb(255, 255, 255);")
        self.security.setObjectName("security")
        self.healthy = QtWidgets.QRadioButton(Register)
        self.healthy.setGeometry(QtCore.QRect(180, 310, 89, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.healthy.setFont(font)
        self.healthy.setStyleSheet("color: rgb(255, 255, 255);")
        self.healthy.setObjectName("healthy")
        self.label_9 = QtWidgets.QLabel(Register)
        self.label_9.setGeometry(QtCore.QRect(30, 350, 49, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Register)
        self.label_10.setGeometry(QtCore.QRect(30, 390, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Register)
        self.label_11.setGeometry(QtCore.QRect(30, 430, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.password = QtWidgets.QLineEdit(Register)
        self.password.setGeometry(QtCore.QRect(160, 390, 211, 22))
        self.password.setObjectName("password")
        self.password_2 = QtWidgets.QLineEdit(Register)
        self.password_2.setGeometry(QtCore.QRect(180, 430, 191, 22))
        self.password_2.setObjectName("password_2")
        self.browse = QtWidgets.QPushButton(Register)
        self.browse.setGeometry(QtCore.QRect(150, 350, 111, 24))
        self.browse.setObjectName("pushButton")

        self.retranslateUi(Register)
        QtCore.QMetaObject.connectSlotsByName(Register)

    def retranslateUi(self, Register):
        _translate = QtCore.QCoreApplication.translate
        Register.setWindowTitle(_translate("Register", "Form"))
        self.label_2.setText(_translate("Register", "REGISTER FOR AN ACCOUNT"))
        self.label_3.setText(_translate("Register", "username"))
        self.label_4.setText(_translate("Register", "contact"))
        self.label_5.setText(_translate("Register", "email"))
        self.label_6.setText(_translate("Register", "work code"))
        self.label_7.setText(_translate("Register", "sector of work"))
        self.submit.setText(_translate("Register", "submit"))
        self.cancel.setText(_translate("Register", "cancel"))
        self.security.setText(_translate("Register", "security"))
        self.healthy.setText(_translate("Register", "healthy"))
        self.label_9.setText(_translate("Register", "photo"))
        self.label_10.setText(_translate("Register", "password"))
        self.label_11.setText(_translate("Register", "confirm password"))
        self.browse.setText(_translate("Register", "Browse image"))

