# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_welcome(object):
    def setupUi(self, welcome):
        welcome.setObjectName("welcome")
        welcome.resize(1100, 670)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/camera.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        welcome.setWindowIcon(icon)
        welcome.setStyleSheet("\n"
"\n"
"#welcome{\n"
"\n"
"background-color: rgb(13, 30, 64);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.title = QtWidgets.QLabel(welcome)
        self.title.setGeometry(QtCore.QRect(430, 230, 301, 41))
        self.title.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 700 24pt \"Calibri\";")
        self.title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.title.setObjectName("title")
        self.login = QtWidgets.QPushButton(welcome)
        self.login.setGeometry(QtCore.QRect(500, 290, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.login.setFont(font)
        self.login.setStyleSheet("#login{\n"
"background-color: rgb(48, 131, 59);\n"
"border-radius: 15px;\n"
"color: white;\n"
"padding: 10px 20px;\n"
"}\n"
"\n"
"#login:hover {\n"
"background-color: #0D1E40;\n"
"border-radius: 15px;\n"
"color: white;\n"
"}\n"
"")
        self.login.setObjectName("login")
        self.label = QtWidgets.QLabel(welcome)
        self.label.setGeometry(QtCore.QRect(430, 40, 221, 191))
        self.label.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-radius: 50px;")
        self.label.setPixmap(QtGui.QPixmap("resources/camera.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(welcome)
        self.label_2.setGeometry(QtCore.QRect(290, 520, 741, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(welcome)
        QtCore.QMetaObject.connectSlotsByName(welcome)

    def retranslateUi(self, welcome):
        _translate = QtCore.QCoreApplication.translate
        welcome.setWindowTitle(_translate("welcome", "Smart Camera System"))
        self.title.setText(_translate("welcome", "Smart Camera Sytem"))
        self.login.setText(_translate("welcome", "Login"))
        self.label_2.setText(_translate("welcome", "Better Interaction With Camera, violent Alerts And Facial Recorgnition"))

